# Generated by Django 6.0.5 on 2026-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_course_major_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lostitempost",
            name="place",
            field=models.TextField(blank=True, null=True),
        ),
    ]
