# Generated by Django 6.0.5 on 2026-05-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_lostitempost_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarship",
            name="minimum_amount",
        ),
        migrations.AddField(
            model_name="scholarship",
            name="amount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
