# Generated by Django 6.0.5 on 2026-05-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_scholarship_minimum_amount_scholarship_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitempost',
            name='img_file_path',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
