# Generated by Django 6.0.5 on 2026-05-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lostitempost_img_file_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitempost',
            old_name='img_file_path',
            new_name='lost_item_img',
        ),
    ]
