# Generated by Django 6.0.5 on 2026-05-27 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_img_file_path_lostitempost_lost_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusEdge',
            fields=[
                ('edge_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_walkable', models.BooleanField(default=True)),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='core.place')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='core.place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAlias',
            fields=[
                ('alias_id', models.AutoField(primary_key=True, serialize=False)),
                ('alias_name', models.CharField(max_length=255)),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, to='core.place')),
            ],
        ),
    ]
