# Generated by Django 6.0.5 on 2026-05-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_campusedge_placealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_group_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
