# Generated by Django 6.0.5 on 2026-05-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reservation_reservation_group_id_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitempost',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
