# Generated by Django 6.0.5 on 2026-05-31 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_create_time_comment_is_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('opinion_1', models.TextField()),
                ('opinion_2', models.TextField()),
                ('publish_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('total_vote_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['publish_date'], name='idx_topic_publish_date')],
            },
        ),
        migrations.CreateModel(
            name='TopicComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('select_opinion', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default=0)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('topic', models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicCommentLike',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(db_column='comment_id', on_delete=django.db.models.deletion.CASCADE, to='core.topiccomment')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='TopicVote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('select_opinion', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('topic', models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
            ],
        ),
        migrations.AddIndex(
            model_name='topiccomment',
            index=models.Index(fields=['topic', '-like_count', '-comment_id'], name='idx_comment_topic_like'),
        ),
        migrations.AddConstraint(
            model_name='topiccommentlike',
            constraint=models.UniqueConstraint(fields=('comment', 'student'), name='unique_comment_like'),
        ),
        migrations.AddIndex(
            model_name='topicvote',
            index=models.Index(fields=['topic'], name='idx_vote_topic'),
        ),
        migrations.AddConstraint(
            model_name='topicvote',
            constraint=models.UniqueConstraint(fields=('topic', 'student'), name='unique_topic_vote'),
        ),
    ]
